server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;

    root  /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    # /  -> index.html (default)
    # /login -> /login.html, /admin -> /admin.html
    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
